### ISSUE TITLE
Add LAYERRECOMMENDS for swupdate

### ISSUE THREAD

**Issue by bachp** [meta-homeassistant/meta-homeassistant#100]
This coincidentally triggered a new update on layerindex which highlights that we should have LAYERRECOMMENDS for meta-swupdate:

https://layers.openembedded.org/layerindex/updates/38998/

`ERROR: Unable to read /opt/workdir/https___github_com_bachp_meta-homeassistant_git/dynamic-layers/swupdate/recipes-images/swus/update-image-core-image-homeassistant.bb: Traceback (most recent call last):
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/command.py", line 91, in runCommand
    result = command_method(self, commandline)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/command.py", line 571, in parseRecipeFile
    envdata = command.cooker.databuilder._parse_recipe(config_data, fn, appendfiles, mc)['']
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/cookerdata.py", line 505, in _parse_recipe
    bb_data = bb.parse.handle(bbfile, bb_data)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/parse/__init__.py", line 107, in handle
    return h['handle'](fn, data, include, baseconfig)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/parse/parse_py/BBHandler.py", line 137, in handle
    statements.eval(d)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/parse/ast.py", line 20, in eval
    statement.eval(data)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/parse/ast.py", line 314, in eval
    bb.parse.BBHandler.inherit(self.classes, self.filename, self.lineno, data)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/parse/parse_py/BBHandler.py", line 67, in inherit
    raise ParseError("Could not inherit file %s" % (file), fn, lineno)
bb.parse.ParseError: ParseError at /opt/workdir/https___github_com_bachp_meta-homeassistant_git/dynamic-layers/swupdate/recipes-images/swus/update-image-core-image-homeassistant.bb:6: Could not inherit file classes/swupdate.bbclass`

I have added meta-swupdate to the meta-homeassistant:mickledore LayerBranch to avoid it throwing an error on the next update run, but if we added the LAYERRECOMMENDS it would be automatically detected I believe.

https://layers.openembedded.org/layerindex/branch/mickledore/layer/meta-homeassistant/

_Originally posted by @moto-timo in https://github.com/meta-homeassistant/meta-homeassistant/issues/99#issuecomment-1894579386_

**Comment by moto-timo** [comment]
Fixed with #107
