### ISSUE TITLE
python3-aioshelly_6.0.0 throws error when homeassistant boots

### ISSUE THREAD

**Issue by Gerry546** [meta-homeassistant/meta-homeassistant#92]
Upgraded python3-aioshelly to 6.0.0 for 2023.9.0 release.
Throws an error in the background. 

Places like [here](https://git.edevau.net/onkelbeh/HomeAssistantRepository/issues/2217) have reported a similar error like below.

Nov 06 21:42:12 reterminal hass[956]: 2023-11-06 21:42:12.133 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform homeassistant.components.shelly.config_flow
Nov 06 21:42:12 reterminal hass[956]: Traceback (most recent call last):
Nov 06 21:42:12 reterminal hass[956]:   File "/usr/lib/python3.11/site-packages/homeassistant/loader.py", line 838, in get_platform
Nov 06 21:42:12 reterminal hass[956]:     cache[full_name] = self._import_platform(platform_name)
Nov 06 21:42:12 reterminal hass[956]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 06 21:42:12 reterminal hass[956]:   File "/usr/lib/python3.11/site-packages/homeassistant/loader.py", line 855, in _import_platform
Nov 06 21:42:12 reterminal hass[956]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
Nov 06 21:42:12 reterminal hass[956]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 06 21:42:12 reterminal hass[956]:   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
Nov 06 21:42:12 reterminal hass[956]:     return _bootstrap._gcd_import(name[level:], package, level)
Nov 06 21:42:12 reterminal hass[956]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 06 21:42:12 reterminal hass[956]:   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
Nov 06 21:42:12 reterminal hass[956]:   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
Nov 06 21:42:12 reterminal hass[956]:   File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
Nov 06 21:42:12 reterminal hass[956]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Nov 06 21:42:12 reterminal hass[956]:   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
Nov 06 21:42:12 reterminal hass[956]:   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
Nov 06 21:42:12 reterminal hass[956]:   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
Nov 06 21:42:12 reterminal hass[956]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
Nov 06 21:42:12 reterminal hass[956]:   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
Nov 06 21:42:12 reterminal hass[956]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Nov 06 21:42:12 reterminal hass[956]:   File "/usr/lib/python3.11/site-packages/homeassistant/components/shelly/__init__.py", line 40, in <module>
Nov 06 21:42:12 reterminal hass[956]:     from .coordinator import (
Nov 06 21:42:12 reterminal hass[956]:   File "/usr/lib/python3.11/site-packages/homeassistant/components/shelly/coordinator.py", line 11, in <module>
Nov 06 21:42:12 reterminal hass[956]:     from aioshelly.ble import async_ensure_ble_enabled, async_stop_scanner
Nov 06 21:42:12 reterminal hass[956]:   File "/usr/lib/python3.11/site-packages/aioshelly/ble/__init__.py", line 8, in <module>
Nov 06 21:42:12 reterminal hass[956]:     from bluetooth_data_tools import BLEGAPAdvertisement, parse_advertisement_data
Nov 06 21:42:12 reterminal hass[956]:   File "/usr/lib/python3.11/site-packages/bluetooth_data_tools/__init__.py", line 7, in <module>
Nov 06 21:42:12 reterminal hass[956]:     from .gap import (
Nov 06 21:42:12 reterminal hass[956]:   File "src/bluetooth_data_tools/gap.py", line 99, in init bluetooth_data_tools.gap
Nov 06 21:42:12 reterminal hass[956]: TypeError: 'type' object is not subscriptable

**Comment by Gerry546** [comment]
This issue can
